

services:
  - type: web
    plan: free
    name: app_cost_calculator
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn app_cost_calculator.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
