

services:
  - type: web
    plan: free
    name: app_cost_calculator
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
